firstName = input("what is your first name?\n")
lastName = input("what is your surname?\n")
age = int(input("How old are you?\n"))
color = input("what is your favorite color?\n")
hometown = input("where do you come from?\n")
print("\n")
print("---Your Introduction card---\n")
print(f"Name: {firstName } {lastName} ")
print(f"Age: {age}")
print(f"color:  {color}")
print(f"Hometown: {hometown}")
